matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists: []
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
    default_encoding: utf-8
